import type { Config } from "tailwindcss";

export default {
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"surface-tint": "#565d7a",
				"inverse-primary": "#bec5e6",
				primary: "#000000",
				"surface-bright": "#fcf9f3",
				"outline-variant": "#c6c6ce",
				"on-secondary-container": "#fffbff",
				"on-tertiary-fixed": "#FFFFFF",
				"on-primary": "#ffffff",
				"inverse-surface": "#31312d",
				"on-error": "#ffffff",
				"on-secondary-fixed-variant": "#93000e",
				error: "#ba1a1a",
				"primary-fixed-dim": "#bec5e6",
				"surface-dim": "#dcdad4",
				"secondary-fixed-dim": "#ffb4ac",
				"inverse-on-surface": "#f3f0ea",
				"surface-variant": "#e5e2dc",
				"on-tertiary-container": "#a87d00",
				"on-primary-container": "#7b83a1",
				"on-secondary-fixed": "#410003",
				"tertiary-fixed-dim": "#1e2188",
				"on-tertiary-fixed-variant": "#5c4300",
				"on-primary-fixed-variant": "#3e4661",
				tertiary: "#000000",
				"secondary-fixed": "#ffdad6",
				background: "#fcf9f3",
				"surface-container-high": "#ebe8e2",
				"surface-container-highest": "#e5e2dc",
				"error-container": "#ffdad6",
				outline: "#76767e",
				"surface-container": "#f0eee8",
				"on-secondary": "#ffffff",
				"tertiary-container": "#261a00",
				secondary: "#b51a1e",
				"on-surface-variant": "#45464d",
				"primary-fixed": "#dbe1ff",
				"primary-container": "#121a33",
				"tertiary-fixed": "#ffdfa0",
				"on-primary-fixed": "#121a33",
				"on-background": "#1c1c18",
				"surface-container-low": "#f6f3ed",
				"on-tertiary": "#ffffff",
				"on-error-container": "#93000a",
				"secondary-container": "#d93633",
				surface: "#fcf9f3",
				"on-surface": "#1c1c18",
				"surface-container-lowest": "#ffffff",
			},
			fontFamily: {
				headline: ["Newsreader", "serif"],
				body: ["Manrope", "sans-serif"],
				label: ["Manrope", "sans-serif"],
			},
			borderRadius: {
				DEFAULT: "0px",
				lg: "0px",
				xl: "0px",
				full: "9999px",
			},
		},
	},
} satisfies Config;
